--- 
TrainDataset:
  cls: "FolioSDP"
  args:
    dir_path: "./dataset/Folio/MATC_Folio"
    resize: 512
    aug_prob: 0.0

ValidDataset:
  fromsplit: 0.2

Data:
  Batch_size: 64
  Shuffle: True 

Model: 
  Name: "SP-FolioSDP"

Training: 
  Epochs: 300
  SEED: 2023
  Dropout: 0
Optimizer: 
  Name: "Adam"
  lr: 0.00001
  weight_decay: 0.0001

Loss: 
  Name: "CrossEntropyLoss"
