--- 
TrainDataset:
  cls: "FashionMNISTSDP"
  args:
    dir_path: "./dataset/FMNIST/MNIST_sdp_dp_modified_backup/train" 
    resize: 512
    aug_prob: 0.0

ValidDataset:
  fromsplit: 0.1

Data:
  Batch_size: 64
  Shuffle: True 

Model: 
  Name: "SP-FMNIST_SDP"

Training: 
  Epochs: 300
  SEED: 2023
  Dropout: 0
Optimizer: 
  Name: "Adam"
  lr: 0.00001
  weight_decay: 0.0001

Loss: 
  Name: "CrossEntropyLoss"
