--- 
TrainDataset:
  cls: "FolioSDP"
  args:
    dir_path: "/home/salimkhazem/ssd1To/datasets/Folio/MATC_Folio"
    resize: 512
    aug_prob: 0.0

ValidDataset:
  fromsplit: 0.2

Data:
  Batch_size: 64
  Shuffle: True 

Model: 
  Name: "SP-FolioSDP"

Training: 
  Epochs: 500
  SEED: 2023
  Dropout: 0
Optimizer: 
  Name: "AdamW"
  lr: 0.000001
  weight_decay: 0.1

Loss: 
  Name: "CrossEntropyLoss"
