--- 
TrainDataset:
  cls: "FashionMNISTSDP"
  args:
    dir_path: "/home/GPU/skhazem/Spline-pipeline/spline-attention/data/MNIST_sdp_dp/train"
    resize: 512
    aug_prob: 0.4

ValidDataset:
  fromsplit: 0.1

Data:
  Batch_size: 256
  Shuffle: True 

Model: 
  Name: "SP-FMNIST_SDP"

Training: 
  Epochs: 500
  SEED: 2023
  Dropout: 0
Optimizer: 
  Name: "AdamW"
  lr: 0.000001
  weight_decay: 0.0001

Loss: 
  Name: "CrossEntropyLoss"
